In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.pipeline import Pipeline
from sklearn.metrics import roc_curve, roc_auc_score
from sklearn.metrics import log_loss
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score
from sklearn.model_selection import StratifiedKFold, KFold
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier
import os

In [ ]:

os.chdir(r"C:\Users\dai\Desktop\Machine Learning\Assignments\Assignment 2\santander-customer-satisfaction")
test = pd.read_csv("test.csv")
train = pd.read_csv("train.csv",index_col=0)

In [4]:
X_train = train.drop(['TARGET'], axis=1)
y_train = train['TARGET']
X_test =  test.drop('ID', axis=1)
print(X_train.columns)
print(X_test.columns)

Index(['var3', 'var15', 'imp_ent_var16_ult1', 'imp_op_var39_comer_ult1',
       'imp_op_var39_comer_ult3', 'imp_op_var40_comer_ult1',
       'imp_op_var40_comer_ult3', 'imp_op_var40_efect_ult1',
       'imp_op_var40_efect_ult3', 'imp_op_var40_ult1',
       ...
       'saldo_medio_var29_ult3', 'saldo_medio_var33_hace2',
       'saldo_medio_var33_hace3', 'saldo_medio_var33_ult1',
       'saldo_medio_var33_ult3', 'saldo_medio_var44_hace2',
       'saldo_medio_var44_hace3', 'saldo_medio_var44_ult1',
       'saldo_medio_var44_ult3', 'var38'],
      dtype='object', length=369)
Index(['var3', 'var15', 'imp_ent_var16_ult1', 'imp_op_var39_comer_ult1',
       'imp_op_var39_comer_ult3', 'imp_op_var40_comer_ult1',
       'imp_op_var40_comer_ult3', 'imp_op_var40_efect_ult1',
       'imp_op_var40_efect_ult3', 'imp_op_var40_ult1',
       ...
       'saldo_medio_var29_ult3', 'saldo_medio_var33_hace2',
       'saldo_medio_var33_hace3', 'saldo_medio_var33_ult1',
       'saldo_medio_var33_ult3', 'saldo_m

In [ ]:
#Find out how many principal components explain more than 90% variation 
#taking all the variables except ID and target. 

In [5]:
scaler = StandardScaler().set_output(transform='pandas')
scaler

StandardScaler()

In [6]:
scaler.fit(train)

StandardScaler()

In [7]:
train_scl = scaler.transform(train)

In [8]:
pca = PCA().set_output(transform='pandas')
principalComponents = pca.fit_transform(train_scl)

In [9]:
print(principalComponents.var())

pca0      2.707399e+01
pca1      1.752103e+01
pca2      1.220742e+01
pca3      1.165427e+01
pca4      1.143885e+01
              ...     
pca365    4.467237e-32
pca366    2.876972e-32
pca367    1.458396e-32
pca368    5.768141e-33
pca369    8.347760e-34
Length: 370, dtype: float64


In [10]:
print(np.cumsum(pca.explained_variance_ratio_*100))

[  8.05762983  13.27215478  16.90526807  20.37375463  23.77813001
  26.88785211  29.82036168  32.63604501  35.23816156  37.79180486
  40.0397142   42.16560015  44.27058718  46.30915874  48.29164771
  50.03724272  51.66462642  53.22036044  54.60863802  55.92725736
  57.21591065  58.44761069  59.66811474  60.84500883  61.91802523
  62.97519537  64.00354609  65.0113538   66.00615265  66.96768879
  67.91622603  68.84865855  69.76076367  70.63205855  71.47626761
  72.27715653  73.0114923   73.7249603   74.39956719  75.06426156
  75.7095828   76.33319489  76.95518278  77.56063674  78.15957689
  78.7567035   79.33628716  79.91184486  80.47963815  81.03057113
  81.55043667  82.05825058  82.49871162  82.93137494  83.34919614
  83.75957487  84.16556561  84.5547516   84.93646804  85.30664944
  85.67202008  86.0272589   86.38162433  86.71162887  87.03491902
  87.34328907  87.64792099  87.94904052  88.24647782  88.5402739
  88.82837523  89.1100028   89.38714985  89.6630798   89.92746958
  90.182317

In [13]:
var=(np.cumsum(pca.explained_variance_ratio_*100))

In [14]:
count=(var > 90).sum()
print("no of features that give varaiation more than 90% is: ",count)

no of features that give varaiation more than 90% is:  295


In [13]:
scaler = StandardScaler().set_output(transform='pandas')
prcomp=PCA().set_output(transform='pandas')


In [70]:
#using random forest

In [14]:
rf=RandomForestClassifier(random_state=24)

In [22]:
pipe_train=Pipeline([('SCL',scaler),('PCA',prcomp),('RF',rf)])
pipe_train.fit(X_train,y_train)

Pipeline(steps=[('SCL', StandardScaler()), ('PCA', PCA()),
                ('RF', RandomForestClassifier(random_state=24))])

In [23]:
y_pred=pipe_train.predict(X_test)

In [24]:
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [27]:
submit=pd.DataFrame({'ID':test['ID'],'TARGET':y_pred})

In [28]:
submit.to_csv('rf_sanatander.csv',index=False)

In [ ]:
#using xgb

In [30]:
xgb=XGBClassifier(random_state=24)

In [31]:
pipe_train=Pipeline([('SCL',scaler),('PCA',prcomp),('XGB',xgb)])
pipe_train.fit(X_train,y_train)

Pipeline(steps=[('SCL', StandardScaler()), ('PCA', PCA()),
                ('XGB',
                 XGBClassifier(base_score=None, booster=None, callbacks=None,
                               colsample_bylevel=None, colsample_bynode=None,
                               colsample_bytree=None, device=None,
                               early_stopping_rounds=None,
                               enable_categorical=False, eval_metric=None,
                               feature_types=None, gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=None,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=None, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=None, n_jobs=None,
                               num_parallel_tree=None, random_state=24, ...))])

In [32]:
y_pred=pipe_train.predict(X_test)

In [33]:
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [34]:
submit=pd.DataFrame({'ID':test['ID'],'TARGET':y_pred})

In [35]:
submit.to_csv('xgb_sanatander.csv',index=False)

In [ ]:
#using catboost

In [38]:
cb = CatBoostClassifier(random_state=24)

In [39]:
pipe_train=Pipeline([('SCL',scaler),('PCA',prcomp),('CAB',cb)])
pipe_train.fit(X_train,y_train)

Learning rate set to 0.065477
0:	learn: 0.5954117	total: 175ms	remaining: 2m 55s
1:	learn: 0.5160132	total: 242ms	remaining: 2m
2:	learn: 0.4533151	total: 310ms	remaining: 1m 43s
3:	learn: 0.3994197	total: 376ms	remaining: 1m 33s
4:	learn: 0.3564742	total: 435ms	remaining: 1m 26s
5:	learn: 0.3217460	total: 499ms	remaining: 1m 22s
6:	learn: 0.2938977	total: 561ms	remaining: 1m 19s
7:	learn: 0.2688164	total: 624ms	remaining: 1m 17s
8:	learn: 0.2497463	total: 688ms	remaining: 1m 15s
9:	learn: 0.2318867	total: 759ms	remaining: 1m 15s
10:	learn: 0.2173877	total: 832ms	remaining: 1m 14s
11:	learn: 0.2057972	total: 899ms	remaining: 1m 13s
12:	learn: 0.1955821	total: 963ms	remaining: 1m 13s
13:	learn: 0.1872141	total: 1.03s	remaining: 1m 12s
14:	learn: 0.1812399	total: 1.1s	remaining: 1m 12s
15:	learn: 0.1755017	total: 1.17s	remaining: 1m 11s
16:	learn: 0.1706309	total: 1.23s	remaining: 1m 11s
17:	learn: 0.1669537	total: 1.3s	remaining: 1m 10s
18:	learn: 0.1632237	total: 1.36s	remaining: 1m 10

160:	learn: 0.1271035	total: 9.93s	remaining: 51.8s
161:	learn: 0.1270207	total: 9.98s	remaining: 51.6s
162:	learn: 0.1269441	total: 10s	remaining: 51.5s
163:	learn: 0.1268910	total: 10.1s	remaining: 51.4s
164:	learn: 0.1268199	total: 10.2s	remaining: 51.4s
165:	learn: 0.1267590	total: 10.2s	remaining: 51.3s
166:	learn: 0.1266885	total: 10.3s	remaining: 51.2s
167:	learn: 0.1266087	total: 10.3s	remaining: 51.1s
168:	learn: 0.1265265	total: 10.4s	remaining: 51s
169:	learn: 0.1264561	total: 10.4s	remaining: 50.9s
170:	learn: 0.1263940	total: 10.5s	remaining: 50.8s
171:	learn: 0.1263223	total: 10.5s	remaining: 50.8s
172:	learn: 0.1262589	total: 10.6s	remaining: 50.7s
173:	learn: 0.1261817	total: 10.7s	remaining: 50.6s
174:	learn: 0.1261034	total: 10.7s	remaining: 50.5s
175:	learn: 0.1260189	total: 10.8s	remaining: 50.4s
176:	learn: 0.1259556	total: 10.8s	remaining: 50.3s
177:	learn: 0.1259287	total: 10.9s	remaining: 50.2s
178:	learn: 0.1258381	total: 10.9s	remaining: 50.1s
179:	learn: 0.12

320:	learn: 0.1161616	total: 19.2s	remaining: 40.6s
321:	learn: 0.1161250	total: 19.3s	remaining: 40.6s
322:	learn: 0.1160811	total: 19.3s	remaining: 40.5s
323:	learn: 0.1160217	total: 19.4s	remaining: 40.4s
324:	learn: 0.1159909	total: 19.4s	remaining: 40.4s
325:	learn: 0.1159263	total: 19.5s	remaining: 40.3s
326:	learn: 0.1158680	total: 19.6s	remaining: 40.2s
327:	learn: 0.1158149	total: 19.6s	remaining: 40.2s
328:	learn: 0.1157488	total: 19.7s	remaining: 40.1s
329:	learn: 0.1156873	total: 19.7s	remaining: 40.1s
330:	learn: 0.1156572	total: 19.8s	remaining: 40s
331:	learn: 0.1155899	total: 19.8s	remaining: 39.9s
332:	learn: 0.1155363	total: 19.9s	remaining: 39.9s
333:	learn: 0.1155198	total: 19.9s	remaining: 39.8s
334:	learn: 0.1154589	total: 20s	remaining: 39.7s
335:	learn: 0.1153982	total: 20.1s	remaining: 39.6s
336:	learn: 0.1153434	total: 20.1s	remaining: 39.6s
337:	learn: 0.1152857	total: 20.2s	remaining: 39.5s
338:	learn: 0.1152410	total: 20.2s	remaining: 39.4s
339:	learn: 0.11

480:	learn: 0.1071824	total: 28.5s	remaining: 30.8s
481:	learn: 0.1071491	total: 28.6s	remaining: 30.7s
482:	learn: 0.1071194	total: 28.7s	remaining: 30.7s
483:	learn: 0.1070839	total: 28.7s	remaining: 30.6s
484:	learn: 0.1070322	total: 28.8s	remaining: 30.6s
485:	learn: 0.1069944	total: 28.8s	remaining: 30.5s
486:	learn: 0.1069480	total: 28.9s	remaining: 30.4s
487:	learn: 0.1069159	total: 28.9s	remaining: 30.4s
488:	learn: 0.1068773	total: 29s	remaining: 30.3s
489:	learn: 0.1068348	total: 29.1s	remaining: 30.3s
490:	learn: 0.1067879	total: 29.1s	remaining: 30.2s
491:	learn: 0.1067317	total: 29.2s	remaining: 30.1s
492:	learn: 0.1066959	total: 29.2s	remaining: 30.1s
493:	learn: 0.1066238	total: 29.3s	remaining: 30s
494:	learn: 0.1065733	total: 29.3s	remaining: 29.9s
495:	learn: 0.1065262	total: 29.4s	remaining: 29.9s
496:	learn: 0.1064771	total: 29.5s	remaining: 29.8s
497:	learn: 0.1064035	total: 29.5s	remaining: 29.8s
498:	learn: 0.1063681	total: 29.6s	remaining: 29.7s
499:	learn: 0.10

640:	learn: 0.0998634	total: 38.1s	remaining: 21.4s
641:	learn: 0.0998539	total: 38.2s	remaining: 21.3s
642:	learn: 0.0998101	total: 38.2s	remaining: 21.2s
643:	learn: 0.0997696	total: 38.3s	remaining: 21.2s
644:	learn: 0.0997387	total: 38.4s	remaining: 21.1s
645:	learn: 0.0996892	total: 38.4s	remaining: 21.1s
646:	learn: 0.0996470	total: 38.5s	remaining: 21s
647:	learn: 0.0995928	total: 38.5s	remaining: 20.9s
648:	learn: 0.0995334	total: 38.6s	remaining: 20.9s
649:	learn: 0.0995001	total: 38.7s	remaining: 20.8s
650:	learn: 0.0994453	total: 38.7s	remaining: 20.8s
651:	learn: 0.0993979	total: 38.8s	remaining: 20.7s
652:	learn: 0.0993587	total: 38.9s	remaining: 20.6s
653:	learn: 0.0993148	total: 38.9s	remaining: 20.6s
654:	learn: 0.0992715	total: 39s	remaining: 20.5s
655:	learn: 0.0992074	total: 39s	remaining: 20.5s
656:	learn: 0.0991898	total: 39.1s	remaining: 20.4s
657:	learn: 0.0991446	total: 39.2s	remaining: 20.4s
658:	learn: 0.0991102	total: 39.2s	remaining: 20.3s
659:	learn: 0.0990

800:	learn: 0.0935107	total: 47.7s	remaining: 11.9s
801:	learn: 0.0934827	total: 47.8s	remaining: 11.8s
802:	learn: 0.0934518	total: 47.8s	remaining: 11.7s
803:	learn: 0.0934087	total: 47.9s	remaining: 11.7s
804:	learn: 0.0933773	total: 48s	remaining: 11.6s
805:	learn: 0.0933441	total: 48s	remaining: 11.6s
806:	learn: 0.0933109	total: 48.1s	remaining: 11.5s
807:	learn: 0.0932856	total: 48.1s	remaining: 11.4s
808:	learn: 0.0932416	total: 48.2s	remaining: 11.4s
809:	learn: 0.0932154	total: 48.3s	remaining: 11.3s
810:	learn: 0.0931752	total: 48.3s	remaining: 11.3s
811:	learn: 0.0931462	total: 48.4s	remaining: 11.2s
812:	learn: 0.0931284	total: 48.5s	remaining: 11.1s
813:	learn: 0.0930964	total: 48.5s	remaining: 11.1s
814:	learn: 0.0930681	total: 48.6s	remaining: 11s
815:	learn: 0.0930236	total: 48.6s	remaining: 11s
816:	learn: 0.0929860	total: 48.7s	remaining: 10.9s
817:	learn: 0.0929582	total: 48.8s	remaining: 10.8s
818:	learn: 0.0929212	total: 48.8s	remaining: 10.8s
819:	learn: 0.092883

960:	learn: 0.0884590	total: 57.4s	remaining: 2.33s
961:	learn: 0.0884237	total: 57.4s	remaining: 2.27s
962:	learn: 0.0883782	total: 57.5s	remaining: 2.21s
963:	learn: 0.0883485	total: 57.6s	remaining: 2.15s
964:	learn: 0.0883139	total: 57.6s	remaining: 2.09s
965:	learn: 0.0882784	total: 57.7s	remaining: 2.03s
966:	learn: 0.0882598	total: 57.7s	remaining: 1.97s
967:	learn: 0.0882408	total: 57.8s	remaining: 1.91s
968:	learn: 0.0882043	total: 57.8s	remaining: 1.85s
969:	learn: 0.0881728	total: 57.9s	remaining: 1.79s
970:	learn: 0.0881472	total: 58s	remaining: 1.73s
971:	learn: 0.0881194	total: 58s	remaining: 1.67s
972:	learn: 0.0880792	total: 58.1s	remaining: 1.61s
973:	learn: 0.0880415	total: 58.2s	remaining: 1.55s
974:	learn: 0.0880137	total: 58.2s	remaining: 1.49s
975:	learn: 0.0879874	total: 58.3s	remaining: 1.43s
976:	learn: 0.0879631	total: 58.3s	remaining: 1.37s
977:	learn: 0.0879386	total: 58.4s	remaining: 1.31s
978:	learn: 0.0878921	total: 58.4s	remaining: 1.25s
979:	learn: 0.08

Pipeline(steps=[('SCL', StandardScaler()), ('PCA', PCA()),
                ('CAB',
                 <catboost.core.CatBoostClassifier object at 0x0000029884385010>)])

In [40]:
y_pred=pipe_train.predict(X_test)

In [41]:
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [42]:
submit=pd.DataFrame({'ID':test['ID'],'TARGET':y_pred})

In [43]:
submit.to_csv('catb_sanatander.csv',index=False)

In [ ]:
#using lgbm

In [44]:
lgb = LGBMClassifier(random_state=24)

In [45]:
pipe_train=Pipeline([('SCL',scaler),('PCA',prcomp),('LGB',lgb)])
pipe_train.fit(X_train,y_train)

C:\ProgramData\anaconda3\Lib\site-packages\joblib\externals\loky\backend\context.py:110: UserWarning: Could not find the number of physical cores for the following reason:
found 0 physical cores < 1
Returning the number of logical cores instead. You can silence this warning by setting LOKY_MAX_CPU_COUNT to the number of cores you want to use.
  warnings.warn(
  File "C:\ProgramData\anaconda3\Lib\site-packages\joblib\externals\loky\backend\context.py", line 217, in _count_physical_cores
    raise ValueError(


[LightGBM] [Info] Number of positive: 3008, number of negative: 73012
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.178743 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 94095
[LightGBM] [Info] Number of data points in the train set: 76020, number of used features: 369
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.039569 -> initscore=-3.189348
[LightGBM] [Info] Start training from score -3.189348


Pipeline(steps=[('SCL', StandardScaler()), ('PCA', PCA()),
                ('LGB', LGBMClassifier(random_state=24))])

In [46]:
y_pred=pipe_train.predict(X_test)

In [47]:
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [48]:
submit=pd.DataFrame({'ID':test['ID'],'TARGET':y_pred})

In [49]:
submit.to_csv('lgmb_sanatander.csv',index=False)